### ISSUE TITLE
[BUG] Issue loading EcoEnchants and Eco plugins since voxelsniper 8.4.0

### ISSUE THREAD

**Issue by Thenegal-Marie** [KevinDaGame/VoxelSniper-Reimagined#114]
Hi, 
Since VoxelSniper 8.4.0, I couldn't load EcoEnchant and VoxelSniper at the same time on my Paper server 1.19.3.

**To Reproduce**
1. Run Paper server 1.19.3 with : 
- Voxelsniper 8.4.0
- EcoEnchant 9.15.3
- eco 6.48.3 (eco is required for ecoenchant) 
2. See that kotlin seems to be causing the bug

**Expected behavior**
To load EcoEnchant plugin.

**Desktop:**
 - Minecraft version: 1.19.3
 - Voxelsniper version: 8.4.0
 - Server software : Paper
 
**Additional context**
I didn't have this error before VoxelSniper 8.4.0.

**server log/crash report**
https://pastebin.com/h8Gxi35G

Thanks for reading me

**Comment by KevinDaGame** [comment]
INFO: Have you attempted [8.4.2](https://github.com/KevinDaGame/VoxelSniper-Reimagined/releases/tag/v8.4.2)?

**Comment by Thenegal-Marie** [comment]
Yes all one by one
From 8.4.0 it doesn't work anymore
