### ISSUE TITLE
[BUG] GenerateTreeBrush got different parameters issues

### ISSUE THREAD

**Issue by mdanhier** [KevinDaGame/VoxelSniper-Reimagined#119]
**Describe the bug**
There are 3 problems with the GenerateTreeBrush where issues 1 and 2 are kinda related.

1. Root parameters (rootMin, rootMax, rootLength and rootFloat (I don't know what this one is supposed to do) are supposed to change correctly the roots behavior of the generated tree.
No matter what I change I only get either really really thin straight roots going to 4 directions, or 1 root block in 4 corners (Issue is circled in red).
I also can make the roots competely disappear when lowering rootLength.
The whole problem might be related to the rootMax parameter seemingly being backend-limited to 3.
I can set it to 50 but when using rootMin it auto limits itself to 2 to not exceed maxHeight (which is supposed to be 50).

2. When using minHeight and maxHeight, I'm also somehow backend-limited to a minHeight of 14 and a maxHeight of 19.
We can see this because minHeight and maxHeight auto limits themselves even when the values are supposed to be correct.

3. When generating a rather big tree, the leaves are not connected close enough to the wood and thus are falling (Issue is circled in blue).
The "branch" don't put any wood in it, hence the issue when having long branches (branchLength parameters).

Suggested improvement for the third issue:
Let people choose among all blocks of the game when using Leaves and Wood parameters ?
Don't limit them to woods materials and leaves materials only (allow players to edit metadata of the block maybe, this way we would be able to specify [persistent=true] and have no decay on leaves)
Though this wouldn't fix the base issue where branches are supposed to be made of the tree-material. Here, they are generated as 100% of the leaves material 

**Expected behavior**

**Screenshots**
[see here](https://i.imgur.com/uIny1t3.png)

**Desktop (please complete the following information):**
 - Minecraft version: 1.19.2
 - Voxelsniper version: 8.4.3
 - Server/client software: Purpur 1.19.2-1858

**Additional informations**
I'm Shook#0781 on Discord if you need more informations. I will answer faster here

**Comment by KevinDaGame** [comment]
Apologies for the long wait. I am now looking into this

**Comment by KevinDaGame** [comment]
- [ ] Make leaves persistent
- [ ] Fix roots
- [ ] Fix tree height
- [ ] allow leaf and tree blocks to be swapped out
