### ISSUE TITLE
VoxelBrushManager uses Multimap<Class, String> instead of Map<String, Class>

### ISSUE THREAD

**Issue by Lennart99** [KevinDaGame/VoxelSniper-Reimagined#12]
This doesn't make much sense to me, since you never really want to get the (String) handles from the class, but the other way around is necessary every time another brush is selected

https://github.com/KevinDaGame/VoxelSniper/blob/master/src/main/java/com/thevoxelbox/voxelsniper/VoxelBrushManager.java#L92

**Comment by Crafter-Y** [comment]
The current implementation mapps a Brush Class like `TreeSnipeBrush` to multiple so-called handles. To my understanding, these act like aliases and produce the same result when used. 

It currently uses the type `Multimap<Class<? extends IBrush>, String>`.
With that, it mapps e.g.:
`TreeSnipeBrush.class` => `"t", "tree", "treesnipe"`

It possibly can be changed to a `Map<String, Class<? extends IBrush>>`. I think this is what you meant with this issue.
Now the following mapping would take place:
`"t"` => `TreeSnipeBrush.class`
`"tree"` => `TreeSnipeBrush.class`
`"treesnipe"` => `TreeSnipeBrush.class`
therefore, there would be more data stored then needed.

**Comment by KevinDaGame** [comment]
That makes sense, The main reason we wanted a HashMap is because it's search performance is roughly O(1) while the search performance for a MultiMap at least how we currently do it is O(n) with n being the amount of entries

**Comment by Lennart99** [comment]
Maybe to add to @KevinDaGame's explanation:
The main point was that we had to check every entry of the multimap to find the required brush class, while we never really needed to get the names based on a class (except for unit tests, in which case performance is not as important). I think the amount of extra data stored is relatively small and worth the improvement in my opinion.

https://github.com/KevinDaGame/VoxelSniper-Reimagined/blob/master/VoxelSniperCore/src/main/java/com/github/kevindagame/VoxelBrushManager.java#L139-L143

**Comment by Crafter-Y** [comment]
than, this could be closed now.

**Comment by Lennart99** [comment]
nu sure why it didn't close automatically, closed manually
