### ISSUE TITLE
[FEATURE] Ability to reset brush to "none"

### ISSUE THREAD

**Issue by DogeTennant** [KevinDaGame/VoxelSniper-Reimagined#141]
Hello, as I mentioned earlier today on discord, I'd like to add a feature that would allow me to have no brush selected on my arrow/gunpowder at all.

This is the reason why I want this, copied from discord: "because the default brush is set to "snipe" and some admins that have perms for voxelsniper will accidentally delete blocks, or even worse chests while opening them and having an arrow in their hand, not realizing what's about to happen lol"

**Comment by KevinDaGame** [comment]
This has been added in 8.7.0
