### ISSUE TITLE
[FEATURE] FYI: Updated version of some of my brushes are available

### ISSUE THREAD

**Issue by giltwist** [KevinDaGame/VoxelSniper-Reimagined#162]
Hey, one of the original VoxelPlugineers (proof: https://www.youtube.com/watch?v=2so9UpJ-eRY)  here.  Thanks for keeping this old project alive.  I dunno what version of the old VoxelSniper brushes have survived in your lineage of forks, but back when I was still actively developing VS, several of the more complex brushes (notably triangle and three point circle) were rather...unreliable.  I briefly developed a Forge port of VS where I fixed some of the math.  I just wanted to bring your attention to it if you wanted to make any of those brushes work better.  The key part of that repo is here:

https://github.com/giltwist/T-Square/tree/1.12.2/src/main/java/giltwist/tsquare/items

You obviously won't be able to just direct copy/paste since this is Spigot and that's Forge.  However, the updated logic should be helpful to you.

May the Force be with you.

**Comment by KevinDaGame** [comment]
Interesting to hear from an original voxelsniper dev! We've already rewritten a lot of logic, but I'll see if I can use some of it. 
We've also been abstracting a lot of it, so we aren't even directly using spigot code in the brushes anymore. This should allow us to make a forge port down the line (which we've been working on, but you know, life)
