### ISSUE TITLE
[FEATURE] backport fabric version to 1.20.1 please

### ISSUE THREAD

**Issue by KhaozFrost** [KevinDaGame/VoxelSniper-Reimagined#229]
I was looking forward to the fabric version of this finally getting done but it was started on 1.20.1 and then the following release jumped straight to 1.20.2 :/ could i request backporting it 1 version for cobblemon servers?

**Comment by KevinDaGame** [comment]
Hello, sadly we've currently postponed fabric support. Both Lennart and I are very busy right now and have very little time to invest in developing fabric support.
