### ISSUE TITLE
Stencils

### ISSUE THREAD

**Issue by KevinDaGame** [KevinDaGame/VoxelSniper-Reimagined#35]
This was a feature of the old plugin that has seemingly been removed by ervinchai, the past maintainer. If we were to implement this we would have to redo the file structure since the old version uses binary with item ids. I suggest using json for this

https://www.mcmiddleearth.com/community/wiki/voxel-reference-guide-tutorials/ 

> When this part of the plugin worked I would used the command /b sl oak which would select the custom oak stencil. when I clicked a targeted block with the gun powder the custom oak tree as defined by the stencil would be place on top of the targeted block. because there was more than one oak tree file schematic in the stencil list defined oak tree, it randomizes which one is placed when i click the targeted block.  I have compressed the stencils and stencilLists folders into .zip files 

See examples below. Stencils can (as far as I know) only be opened with a hex editor
[stencils.zip](https://github.com/KevinDaGame/VoxelSniper/files/9012755/stencils.zip)
[StencilLists.zip](https://github.com/KevinDaGame/VoxelSniper/files/9012760/StencilLists.zip)

**Comment by KevinDaGame** [comment]
Proposed solution:
* New version will use .schem files.
* First version will **ONLY READ** schem files.
* schem files in a folder will pick a random one
* There will be no backwards compatibility with stencil files

**Comment by Lars2000** [comment]
I would love to use this. Can be very useful for making large forests with different types of trees.
Currently pasting WE schematics one by one, which takes a lot of time.

Some things I would like to see added (if not yet planned already):
- Support for multiple folders. (Tree example: Folders for small, medium, and large trees.)
- Random rotation for more variation
- Pasting without air

**Comment by KevinDaGame** [comment]
TODO

- [ ] Read schematic files
- [ ] Folder support (pick random)
- [ ] Paste mode
- [ ] Rotation
- [ ] Flipping
- [ ] Brush info

**Comment by KevinDaGame** [comment]
@Lars2000 We've got a beta going for the stencil brush! https://github.com/KevinDaGame/VoxelSniper-Reimagined/releases/tag/v8.12.0-beta.1
