### ISSUE TITLE
[BUG] Performance issues

### ISSUE THREAD

**Issue by KevinDaGame** [KevinDaGame/VoxelSniper-Reimagined#64]
**Describe the bug**
Performance issues in version 8.2.0

**To Reproduce**
1. Install v8.2.0
2. Use erode brush at size 10

**Expected behavior**
It should be faster

**Desktop (please complete the following information):**
 - Minecraft version: 1.19.2
 - Voxelsniper version: 8.2.0
 - Server/client software: Spigot

**Comment by Lennart99** [comment]
Fixed https://github.com/KevinDaGame/VoxelSniper-Reimagined/pull/66
