### ISSUE TITLE
[BUG] Can't use brushes effectively past world height

### ISSUE THREAD

**Issue by roeyb1** [KevinDaGame/VoxelSniper-Reimagined#65]
**Description**:
Using a brush while the player is above the world height limit will truncate the raycast and use the brush as if the targeted block was exactly at the worldheight.

**Repro steps**:
- Fly above the world height limit (y=320)
- Use the ball tool
- Target a block on the ground and right click

**Expected**:
Ball appears on the ground

**Actual**:
Ball appears in the air at the height limit.

Minecraft version: 1.19.2
Voxelsniper version: 8.1.3
Server/client software: Spigot

**Comment by Lennart99** [comment]
Note to self: Version 8.1.3 still uses old tracing methods. Will need to check if the bug also exists in the new code before fixing.

**Comment by Lennart99** [comment]
- Fixed in 8.2.1 (https://github.com/KevinDaGame/VoxelSniper-Reimagined/pull/67)
