### ISSUE TITLE
[FEATURE] Worldguard/PlotSquared Support

### ISSUE THREAD

**Issue by tjtanjin** [KevinDaGame/VoxelSniper-Reimagined#79]
**Is your feature request related to a problem? Please describe.**
Support for worldguard & plotsquared

**Describe the solution you'd like**
Currently, I have a worldguard/plotsquared setup on a creative server and it'd be great if voxelsniper also adheres to the plot permissions of each player (current situation allows players to grief roads with voxel).

**Comment by KevinDaGame** [comment]
This has been implemented in version 8.4
