### ISSUE TITLE
[TECHNICAL DEBT] Make an abstract class for brushes that change multiple block types

### ISSUE THREAD

**Issue by KevinDaGame** [KevinDaGame/VoxelSniper-Reimagined#86]
Examples: ExtrudeBrush, PullBrush, OceanBrush, FlatOceanBrush, ErodeBrush

**Comment by Lennart99** [comment]
Isn't this already covered by the BrushOperations added in #82 ?

**Comment by KevinDaGame** [comment]
Yes it is, closing this issue
